### PR TITLE
Add warning when writing to postgis with proj4, but no SRID

### PR DESCRIPTION
**Pull request by etiennebr**
Fix #102 (will wait for real test on Travis)

### CODE REVIEW

**Comment by etiennebr** [comment]
Yes, sorry; I was waiting for the travis tests, but it takes a while. Didn't expect to get merged so fast! I'll complete the PR when I have a few more minutes with postgis.

I don't see how postgis could add a new proj4 string though, since it only receives an srid in [`AddGeometryColumn`](http://postgis.org/docs/AddGeometryColumn.html) and [`ST_GeomFromText`](http://postgis.org/docs/ST_GeomFromText.html). Any tips ?

**Comment by edzer** [comment]
Ah, I thought you meant postgis as a system, but you meant the sf write interface. Yes, this is something to sort out.

**Comment by etiennebr** [comment]
@edzer, I see you merged all the pull requests. Maybe this is intentional, but if not, here are two tricks that really helped me, I hope you find them useful: 

1. You can checkout pull requests before merging them to master: https://gist.github.com/piscisaureus/3342247
2. Clean pull requests: http://stackoverflow.com/questions/6102297/how-do-i-clean-up-my-github-fork-so-i-can-make-clean-pull-requests

**Comment by edzer** [comment]
Thanks, helpful! Yeah, I've got to learn this branching stuff better.

**Pull request merged**
