### PR TITLE
Overwrite argument

### PR DESCRIPTION
**Pull request by Nowosad**
#274 Changes made:
1. Overwrite argument added to the st_write function
2. Overwrite argument from the st_write_db function renamed to drop

@edzer Please let me know what do you think about these changes.

### CODE REVIEW

**Comment by edzer** [comment]
For how many drivers did you test this? What if `dsn` is `.`, or another directory? What if a data source consists of multiple files (like a shapefile, or another)? 

I feel rather uneasy taking responsibility for code that looks OK and works for a few drivers but may have unforeseen consequences for others. Why not ask GDAL do delete the dsn? In that case the driver implementer decides what should happen, and if it is reasonable to do this.

**Comment by Nowosad** [comment]
http://rpubs.com/j_n/st_write - there you have some tests.

**Comment by edzer** [comment]
What happens if you do
```r
st_write(meuse_sf, system.file("shape", package="sf"), "nc", overwrite = TRUE)
```
?

**Comment by Nowosad** [comment]
> st_write(st_as_sf(meuse), system.file("shape", package="sf"), "nc", overwrite = TRUE)
Error: Could not guess driver for /home/username/R/x86_64-redhat-linux-gnu-library/3.3/sf/shape

**Comment by edzer** [comment]
```r
st_write(st_as_sf(meuse), system.file("shape", package="sf"), "nc", driver = "ESRI Shapefile", overwrite = TRUE)
```

**Comment by Nowosad** [comment]
```
 Error in CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  : 
  Dataset already exists. 
```

However, (correct me if I'm wrong) - it should failed, but with a different error message. Let's try these examples:

```
nc = st_read(dsn = system.file("shape", package="sf"), layer = "nc", driver = "ESRI Shapefile") #failed
nc = st_read(dsn = system.file("shape", package="sf"), driver = "ESRI Shapefile") #failed
nc = st_read(system.file("shape/nc.shp", package="sf")) #works
```

Therefore, if we are unable to read a file this way, we should be also unable to write it this way.

**Comment by edzer** [comment]
Sorry Jakub, I appreciate your efforts very much, but I don't think we should go this way. In sf, we interface to GDAL for reading and writing data, for good reasons, and we should use this same interface if we want to delete data sources. We can then thank (or blame) the driver implementer when it doesn't do what we had in mind.

**Comment by Nowosad** [comment]
Understood. I will think of a gdal way to do it.

**Pull request closed without merging**
