### PR TITLE
Add warning when writing to postgis with proj4, but no SRID

### PR DESCRIPTION
**Pull request by etiennebr**
Please don't merge yet, I need to wait for travis to finish.

Ref to #158, #102

### CODE REVIEW

**Comment by etiennebr** [comment]
@edzer, would you mind having a look? I'm not familiar with tests using `Rout.save`, and I don't understand how travis tests can pass since I haven't updated the `pg.Rout.save`, yet. 

Running locally, I get a warning at pg.Rout.save#L18 
```r
x = st_read_db(conn, query = "select * from meuse_tbl limit 30;")
# Warning message:
# In st_read_db(conn, query = "select * from meuse_tbl limit 30;") :
#   argument table missing: returning object without crs
```
Also #L78, 
```r
print(st_layers("PG:dbname=empty"))
# Cannot open data source PG:dbname=empty
#  Show Traceback
#  
#  Rerun with Debug
#  Error in CPL_get_layers(dsn, options, do_count) : Open failed. In addition: Warning message:
# In CPL_get_layers(dsn, options, do_count) :
#   GDAL Error 1: PQconnectdb failed.
# FATAL:  database "empty" does not exist
```
So I didn't know what I should update exactly.

I've merged the tests so I could add my user for R CMD CHECK.

**Comment by edzer** [comment]
Hi, I liked moving the test into testthat conditionals, but some of your new checks didn't work iirc. Do you want me to finish this?

**Comment by etiennebr** [comment]
Hi Edzer, thanks for the offer. I was away from computer for a few days, I plan to finish it this week. I'll resolve conflicts and make a proper PR. I wasn't sure about migrating the tests, but while moving to testthat and setting up my own database for testing I discovered the function had difficulties handling schemas, so I went down a rabbit hole fixing this, but I think I can finish it probably today. The failing tests are about missing/empty tables and binary written tables crs (test_postgis.R#L83 and #L86).

**Comment by edzer** [comment]
Great, I'll wait for that for the 0.3 releas.

**Comment by etiennebr** [comment]
Ready to merge

**Pull request merged**
