### PR TITLE
Update DESCRIPTION

### PR DESCRIPTION
**Pull request by mpadge**

### CODE REVIEW

**Comment by edzer** [comment]
This was not a typo; renaming the package is a bit more involved than that.

**Comment by mpadge** [comment]
Sorry Edzer, I meant it more just as a prompt to circumvent the potentially confusing steps of having to load `sfr` in order to access the `sf` package

**Comment by Nowosad** [comment]
@edzer - I also have s similar concern. Why the repo for sf package has a "sfr" name?

**Comment by edzer** [comment]
The proposal was called "simple features for R", as is the project that carries it out. The package it produces is called "sf", and is in the project directory. I can rename the repo or package, but what is the concern when in a short while most people will install from CRAN?

**Pull request closed without merging**
