### PR TITLE
include MIT and GPL2 licences

### PR DESCRIPTION
**Pull request by etiennebr**
From reading #163, I realized license texts were missing (required by both MIT and GPL2). I think this is the right way to include multiples licenses.

### CODE REVIEW

**Comment by edzer** [comment]
What's the advantage of adding this when DESCRIPTION and the CRAN package site points to the right licenses, and FILE? (see also: "Writing R extensions").

**Comment by nuest** [comment]
In other languages having a `LICENSE` file is common, in R it is actually not. If there is a license file, it normally contains the full text of the license. I find it confusing to see both. Since MIT is much less limiting than GPL, you could just put MIT in there.

**Comment by etiennebr** [comment]
My understanding is that both MIT and GPL2 require the text to be
distributed with the software. Although I agree that MIT would probably be
sufficient, but I'm far from an expert on legal matters.
Le mar. 7 févr. 2017 à 07:22, Daniel Nüst <notifications@github.com> a
écrit :

**Comment by nuest** [comment]
Fair point, and no worries, nobody is a lawyer here..

**Comment by edzer** [comment]
See [WRE](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing): I think the way we do it now is in accordance with what is written there; the license files are in every R distribution, it is not needed to repeat those in every package using them.

**Pull request closed without merging**
